server:
# 端口
  port: 8081
  servlet:
# 项目访问路径
    context-path: /
    session:
      cookie:
# cookie失效时间
        max-age: 100
# session失效时间
      timeout: 100
  tomcat:
# 编码格式
    uri-encoding: UTF-8